

import java.sql.ResultSet;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author isuru
 */
public class AddItem extends javax.swing.JPanel {

    /**
     * Creates new form AddItem
     */
    public AddItem() {
        initComponents();
        try {
            String sql="select max(id) from tblitem";
            ResultSet rs=db.dbConnection().executeQuery(sql);
            if (rs.next()) {
                pid.setText((rs.getInt(1)+1)+"");
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pid = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pprice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cprice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        category = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Product Id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 57, -1, -1));

        pid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pid.setText("Product Id");
        jPanel1.add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Product Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 92, -1, -1));
        jPanel1.add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 181, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Product Price");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 185, -1, -1));
        jPanel1.add(pprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 181, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Customer Price");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 223, -1, -1));
        jPanel1.add(cprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 181, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Category");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 137, -1, -1));

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category", "Baby products‎", "Clothing", "Electronic", "Furniture‎", "Foods" }));
        jPanel1.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 181, -1));

        jButton1.setBackground(new java.awt.Color(23, 105, 170));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if(pname.getText().equals(""))
      {
          JOptionPane.showMessageDialog(null, "Product Name Can not Empty", "please Check", JOptionPane.WARNING_MESSAGE);
      }
      else if(category.getSelectedIndex()==0)
          JOptionPane.showMessageDialog(null, "Select The category", "please Check", JOptionPane.WARNING_MESSAGE);
      else if(!Nubmberic.isNumeric(pprice.getText()))
          JOptionPane.showMessageDialog(null, "Product Price Should be Numberic", "please Check", JOptionPane.WARNING_MESSAGE);
      else if(!Nubmberic.isNumeric(cprice.getText()))
          JOptionPane.showMessageDialog(null, "Customer Price Should be Numberic", "please Check", JOptionPane.WARNING_MESSAGE);
      else{
        String sql="insert into tblitem (name,category,pprice,cprice,qty) values ('"+pname.getText()+"','"+category.getSelectedItem()+"','"+pprice.getText()+"','"+cprice.getText()+"','0')";
      int res=db.idu(sql);
      
      if(res==1){
          JOptionPane.showMessageDialog(null, "Update Successfully Completed ", "Completed ", JOptionPane.INFORMATION_MESSAGE);
        home.center.removeAll();
        //this.setTitle("Add Item");
        GroupLayout layout = new javax.swing.GroupLayout(home.center);
        home.center.setLayout(layout);
        AddItem att = new AddItem();

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));   
      }
      
      else
          JOptionPane.showMessageDialog(null, "Update Not Completed please Check", "Completed ", JOptionPane.ERROR_MESSAGE);
      } 
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> category;
    private javax.swing.JTextField cprice;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pid;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField pprice;
    // End of variables declaration//GEN-END:variables
}
