

import java.sql.ResultSet;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author isuru
 */
public class ChangeMyPassword extends javax.swing.JPanel {

    /**
     * Creates new form ChangeMyPassword
     */
    public ChangeMyPassword() {
        initComponents();
        uname.setText(Login.uname);
        update.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pw1 = new javax.swing.JPasswordField();
        pw2 = new javax.swing.JPasswordField();
        update = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cpw = new javax.swing.JPasswordField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("User Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 69, -1, -1));

        uname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        uname.setText("jLabel2");
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Confirm Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));
        jPanel1.add(pw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 140, -1));

        pw2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pw2KeyReleased(evt);
            }
        });
        jPanel1.add(pw2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 140, -1));

        update.setBackground(new java.awt.Color(22, 160, 133));
        update.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Current Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));
        jPanel1.add(cpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
          String pww2=new String(pw2.getPassword());
          String cpwd=new String(cpw.getPassword());
          String sqlb="select * from tbluser where uname='"+uname.getText()+"' and pwd='"+cpwd+"'";
          try {
            ResultSet rs=db.dbConnection().executeQuery(sqlb);
          if(rs.next())
          {
              db.dbConnection().close();
               String sql="update tbluser set pwd='"+pww2+"' where uname='"+uname.getText()+"'";
        int res = db.idu(sql);
        if(res==1)
        {
        JOptionPane.showMessageDialog(null, "Update Successfully Completed ", "Completed ", JOptionPane.INFORMATION_MESSAGE);
         home.center.removeAll();
       // this.setTitle("Change Password");
        GroupLayout layout = new GroupLayout(home.center);
        home.center.setLayout(layout);
        ChangeMyPassword att = new ChangeMyPassword();

        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(att, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(att, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        }
        else
            JOptionPane.showMessageDialog(null, "Update Not Completed Please Check", "Completed ", JOptionPane.ERROR_MESSAGE);
          }
          else{
              JOptionPane.showMessageDialog(null, "Current User Name is Wrong please Enter Your Correct password ", "Aleart ", JOptionPane.WARNING_MESSAGE);
          }
        } catch (Exception e) {
        }
       
    }//GEN-LAST:event_updateActionPerformed

    private void pw2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pw2KeyReleased
          String pww1=new String(pw1.getPassword());
        String pww2=new String(pw2.getPassword());
        if(pww1.equals(pww2))
        {
        update.setEnabled(true);
        }
        else{
        update.setEnabled(false);
        }
    }//GEN-LAST:event_pw2KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cpw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pw1;
    private javax.swing.JPasswordField pw2;
    private javax.swing.JLabel uname;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
