

import java.sql.ResultSet;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author isuru
 */
public class Foget extends javax.swing.JPanel {

    /**
     * Creates new form Foget
     */
    public Foget() {
        initComponents();
        que.setVisible(false);
        anl.setVisible(false);
        Ans.setVisible(false);
        Check.setVisible(false);
        pl.setVisible(false);
        cpl.setVisible(false);
        pw1.setVisible(false);
        pw2.setVisible(false);
        update.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Uname = new javax.swing.JTextField();
        que = new javax.swing.JLabel();
        anl = new javax.swing.JLabel();
        Ans = new javax.swing.JTextField();
        pl = new javax.swing.JLabel();
        pw1 = new javax.swing.JPasswordField();
        cpl = new javax.swing.JLabel();
        pw2 = new javax.swing.JPasswordField();
        Find = new javax.swing.JButton();
        Check = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        update = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Enter Your User name :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        jPanel1.add(Uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 192, -1));

        que.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        que.setText("Quection");
        jPanel1.add(que, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        anl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        anl.setText("Answer");
        jPanel1.add(anl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));
        jPanel1.add(Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 192, -1));

        pl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pl.setText("Password");
        jPanel1.add(pl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));
        jPanel1.add(pw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 192, -1));

        cpl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cpl.setText("Confirm Password");
        jPanel1.add(cpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        pw2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pw2KeyReleased(evt);
            }
        });
        jPanel1.add(pw2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 192, -1));

        Find.setBackground(new java.awt.Color(230, 126, 34));
        Find.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Find.setForeground(new java.awt.Color(255, 255, 255));
        Find.setText("Find");
        Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindActionPerformed(evt);
            }
        });
        jPanel1.add(Find, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        Check.setBackground(new java.awt.Color(39, 174, 96));
        Check.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Check.setForeground(new java.awt.Color(255, 255, 255));
        Check.setText("Check");
        Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckActionPerformed(evt);
            }
        });
        jPanel1.add(Check, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        jButton3.setBackground(new java.awt.Color(52, 152, 219));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("< Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        update.setBackground(new java.awt.Color(243, 156, 18));
        update.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    Login.LoginPanel.removeAll();
        GroupLayout layout = new javax.swing.GroupLayout(Login.LoginPanel);
        Login.LoginPanel.setLayout(layout);
        LoginSub att = new LoginSub();

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindActionPerformed
        try {
            String sql="select * from tbluser where uname='"+Uname.getText()+"'";
            ResultSet rs=db.dbConnection().executeQuery(sql);
            if(rs.next())
            {
                que.setVisible(true);
                anl.setVisible(true);
                Ans.setVisible(true);
                Check.setVisible(true);
                que.setText("What is "+rs.getString("que")+" ?");
            }
            else{
            JOptionPane.showMessageDialog(null, "No Maching found "+Uname.getText(), "Invalied: ", JOptionPane.WARNING_MESSAGE);
            }
            db.dbConnection().close();
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_FindActionPerformed

    private void CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckActionPerformed
   try{
        String sql="select * from tbluser where uname='"+Uname.getText()+"' and anw='"+Ans.getText()+"'";
            ResultSet rs=db.dbConnection().executeQuery(sql);
            if(rs.next())
            {
                pl.setVisible(true);
                cpl.setVisible(true);
                pw1.setVisible(true);
                pw2.setVisible(true);
                update.setVisible(true);
                update.setEnabled(false);
                Uname.setEnabled(false);
            }
            else{
            JOptionPane.showMessageDialog(null, "No Maching found "+Ans.getText(), "Invalied: ", JOptionPane.WARNING_MESSAGE);
            }
            db.dbConnection().close();
        } catch (Exception e) {
        }
        
        
        
    }//GEN-LAST:event_CheckActionPerformed

    private void pw2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pw2KeyReleased
        String pww1=new String(pw1.getPassword());
        String pww2=new String(pw2.getPassword());
        if(pww1.equals(pww2))
        {
        update.setEnabled(true);
        }
        else{
        update.setEnabled(false);
        }
        
    }//GEN-LAST:event_pw2KeyReleased

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
       String pww2=new String(pw2.getPassword());
        String sql="update tbluser set pwd='"+pww2+"' where uname='"+Uname.getText()+"'";
        int res = db.idu(sql);
        if(res==1)
        {
        JOptionPane.showMessageDialog(null, "Update Successfully Completed ", "Completed ", JOptionPane.INFORMATION_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(null, "Update Not Completed Please Check", "Completed ", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_updateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ans;
    private javax.swing.JButton Check;
    private javax.swing.JButton Find;
    private javax.swing.JTextField Uname;
    private javax.swing.JLabel anl;
    private javax.swing.JLabel cpl;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pl;
    private javax.swing.JPasswordField pw1;
    private javax.swing.JPasswordField pw2;
    private javax.swing.JLabel que;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
