
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author isuru
 */
public class Grn extends javax.swing.JPanel {

    /**
     * Creates new form Grn
     */
    public Grn() {
        initComponents();
        try {
            String sql3="select max(gid) from tblgrn";
               // int gid=1;
                ResultSet rs1=db.dbConnection().executeQuery(sql3); 
                if(rs1.next())
                {
                    int a=(Integer.parseInt(rs1.getString(1)))+1;
                    grnid.setText(a+"");
                }
                else{
                 grnid.setText(1+"");
                }
                db.dbConnection().close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        grnid = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        stotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        discount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grnid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        grnid.setText("GRN Number : ");
        jPanel1.add(grnid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("GRN Number");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        pid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pidKeyReleased(evt);
            }
        });
        jPanel1.add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 55, 81, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Product Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 58, -1, -1));
        jPanel1.add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 55, 130, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Quantity");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 58, -1, -1));

        qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyKeyReleased(evt);
            }
        });
        jPanel1.add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 55, 70, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Price");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 58, -1, -1));
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 55, 81, -1));

        jButton1.setBackground(new java.awt.Color(155, 89, 182));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 54, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Prodct Name", "Price", "Quantity", "Total"
            }
        ));
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 104, 1072, 299));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Sub Total");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 433, -1, -1));

        stotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                stotalKeyReleased(evt);
            }
        });
        jPanel1.add(stotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 430, 207, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Discount");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 471, -1, -1));

        discount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                discountKeyReleased(evt);
            }
        });
        jPanel1.add(discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 468, 207, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Total");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 509, -1, -1));

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalKeyReleased(evt);
            }
        });
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 506, 207, -1));

        jButton2.setBackground(new java.awt.Color(52, 152, 219));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1038, 560, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Product Id");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 58, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1175, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pidKeyReleased
        try {
            if(evt.getKeyCode()==10)
            {
                
                if(pid.getText().equals(""))
                {
                    discount.grabFocus();
                }
                else{
                ResultSet rs=db.dbConnection().executeQuery("select * from tblitem where id='"+pid.getText()+"'");
                if(rs.next())
                {
                    pname.setText(rs.getString("name"));
                    price.setText(rs.getString("pprice"));
                    qty.grabFocus();
                }
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_pidKeyReleased

    private void qtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyReleased
         if(evt.getKeyCode()==10)
           jButton1.doClick();
    }//GEN-LAST:event_qtyKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel df=(DefaultTableModel) jTable1.getModel();
        String a1=price.getText();
    String a2=qty.getText();
    
           int qtyy=Integer.parseInt(qty.getText());
           if( qtyy<1)
           {
                 JOptionPane.showMessageDialog(null, qtyy+" No Avalable in stock Please Enter Avalable Stock", "Warning!!", JOptionPane.WARNING_MESSAGE);
           }
           else
           {
    int b=Integer.parseInt(a2);
    double b1=Double.parseDouble(a1);
    double b2=b*b1;
     String aaas=new DecimalFormat("0.00").format(b2);
    
    //jTextField11.grabFocus();
    // String aaasp=new DecimalFormat("0.00").format(b1);
        Vector v=new Vector();
        v.add(pid.getText());
        v.add(pname.getText());
        v.add(price.getText());
         v.add(qty.getText());
         v.add(aaas);
        df.addRow(v);
        pid.setText("");
        pname.setText("");
        price.setText("");
        qty.setText("");
        pid.grabFocus();
        double total = 0.00;
                for (int h = 0; h < df.getRowCount(); h++) {
                    String jk = jTable1.getValueAt(h, 4).toString();

                    double lk = Double.parseDouble(jk);
                    total += lk;
                      String aaasl=new DecimalFormat("0.00").format(total);
                    stotal.setText(aaasl + "");
                    
                }
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void discountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discountKeyReleased
        if(evt.getKeyCode()==10)
       {
           double stt=Double.parseDouble(stotal.getText());
           double dis=Double.parseDouble(discount.getText());
           double tt=stt*dis/100;
           String ttl=new DecimalFormat("0.00").format((stt-tt));
           total.setText(ttl+"");
           total.grabFocus();
           
       }
    }//GEN-LAST:event_discountKeyReleased

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
         int a=evt.getKeyCode();
        if (a==127) {
            
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel();

        int[] rows = jTable1.getSelectedRows();
        for (int i = 0; i < rows.length; i++) {
            model.removeRow(rows[i] - i);
        }
        double total = 0.00;
                for (int h = 0; h < model.getRowCount(); h++) {
                    String jk = jTable1.getValueAt(h, 4).toString();

                    double lk = Double.parseDouble(jk);
                    total += lk;
                      String aaasl=new DecimalFormat("0.00").format(total);
                    stotal.setText(aaasl + "");
                    
        
                }
                if(model.getRowCount()==0)
                    stotal.setText("0.00");
                
        }
    }//GEN-LAST:event_jTable1KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            if (jTable1.getRowCount()==0) {
            JOptionPane.showMessageDialog(null, "the table is empty ", "Error",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                
                String sql1="insert into tblgrn (stotal,discount,total,gdate,gtime) values ('"+stotal.getText()+"','"+discount.getText()+"','"+total.getText()+"','"+home.date.getText()+"','"+home.time.getText()+"')";
                db.idu(sql1);
                String sql3="select max(gid) from tblgrn";
                int gid=1;
                ResultSet rs1=db.dbConnection().executeQuery(sql3);
                if(rs1.next())
                {
                    gid=rs1.getInt(1);
                }
                DefaultTableModel df=(DefaultTableModel) jTable1.getModel();
                for (int i = 0; i < jTable1.getRowCount(); i++) {
                String s0 = gid+"";
                String s1 = df.getValueAt(i, 0).toString();
                String s2 = df.getValueAt(i, 2).toString();
                String s3 = df.getValueAt(i, 3).toString();
               
               
                
                String sql2="insert into grnitem values('" + s0 + "','" + s1 + "','" + s2 + "','" + s3 + "')";
                db.idu(sql2);
                 String sql5="update tblitem set qty=qty+'" + s3 + "' where id='" + s1 + "' ";
                    System.out.println(sql5);
                 db.idu(sql5);
//                String sql4="select max(gid) from tblgrn";
//               // int gid=1;
//                ResultSet rs4=db.dbConnection().executeQuery(sql4); 
//                if(rs4.next())
//                {
//                     int a=(Integer.parseInt(rs1.getString(1)))+1;
//                    grnid.setText(a+"");
//                }
//                else{
//                 grnid.setText(1+"");
//                }
               
                          home.center.removeAll();
       // this.setTitle("Change Password");
        GroupLayout layout = new javax.swing.GroupLayout(home.center);
        home.center.setLayout(layout);
        Grn att = new Grn();

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                        
            }
            }
            db.dbConnection().close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void totalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalKeyReleased
        if(evt.getKeyCode()==121)
            jButton2.doClick();
    }//GEN-LAST:event_totalKeyReleased

    private void stotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stotalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_stotalKeyReleased

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField discount;
    private javax.swing.JLabel grnid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField price;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField stotal;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
