
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author isuru
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setTitle("Home");
        uname.setText(Login.usname);
        if(Login.utype.equals("1"))
        {
            utype.setText("Admin");
        }
        else if(Login.utype.equals("0"))
        {
            utype.setText("Genaral User");
        }
        if (Login.utype.equals("0"))
        {
            sreq.setVisible(false);
            vstock.setEnabled(false);
            vinvoice.setEnabled(false);
            vgrn.setEnabled(false);
            
        }
        try {
            new Thread(new Runnable() {

            @Override
            public void run() {
                while (true) {
                    Date d = new Date();
                    String dt = d.toString();
                    String ar[] = dt.split(" ");
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                       // Logger.getLogger(time1.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    // System.out.println(ar[3]);
                    time.setText(ar[3]);
                    try {
                        String[] s = time.getText().split(":");
                        String asl = s[2];
                        // System.out.println(asl);
                        int a = Integer.parseInt(asl);
                        int c = a % 5;
                        if(c==0)
                        {
                             try {
            String sql="select count(id) from tbluser Where active='0'";
            ResultSet rs=db.dbConnection().executeQuery(sql);
            if(rs.next())
            {
                sreq.setText("Sign Up Request : "+rs.getInt(1)+"");
            }
            db.dbConnection().close();
        } catch (Exception e) {
        }
                        }
                        
                    } catch (Exception e) {
                    }
                }
            }
        }).start();
        } catch (Exception e) {
        }
         Date d = new Date();
        SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");
        String dt = sd.format(d);
        date.setText(dt);
        try {
            String sql="select count(id) from tbluser Where active='0'";
            ResultSet rs=db.dbConnection().executeQuery(sql);
            if(rs.next())
            {
                sreq.setText("Sign Up Request : "+rs.getInt(1)+"");
            }
            db.dbConnection().close();
        } catch (Exception e) {
        }
         center.removeAll();
        this.setTitle("Add Item");
        GroupLayout layout = new javax.swing.GroupLayout(center);
        home.center.setLayout(layout);
        Welcome att = new Welcome();

        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(att, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(att, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        vstock = new javax.swing.JButton();
        cinvoice = new javax.swing.JButton();
        vinvoice = new javax.swing.JButton();
        grnbtn = new javax.swing.JButton();
        vgrn = new javax.swing.JButton();
        vgrn1 = new javax.swing.JButton();
        setting = new javax.swing.JButton();
        center = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        signoutt = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        utype = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sreq = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(107, 177, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setBackground(new java.awt.Color(85, 160, 204));
        add.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add Item");
        add.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/30-512.png"))); // NOI18N
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 23, 130, 39));

        vstock.setBackground(new java.awt.Color(85, 160, 204));
        vstock.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        vstock.setForeground(new java.awt.Color(255, 255, 255));
        vstock.setText("View Stock");
        vstock.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/online-store.png"))); // NOI18N
        vstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vstockActionPerformed(evt);
            }
        });
        jPanel1.add(vstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, 130, 39));

        cinvoice.setBackground(new java.awt.Color(85, 160, 204));
        cinvoice.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cinvoice.setForeground(new java.awt.Color(255, 255, 255));
        cinvoice.setText("Add Invoice");
        cinvoice.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/receipt.png"))); // NOI18N
        cinvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinvoiceActionPerformed(evt);
            }
        });
        jPanel1.add(cinvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, 130, 39));

        vinvoice.setBackground(new java.awt.Color(85, 160, 204));
        vinvoice.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        vinvoice.setForeground(new java.awt.Color(255, 255, 255));
        vinvoice.setText("All Invoice");
        vinvoice.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/file.png"))); // NOI18N
        vinvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vinvoiceActionPerformed(evt);
            }
        });
        jPanel1.add(vinvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 173, 130, 39));

        grnbtn.setBackground(new java.awt.Color(85, 160, 204));
        grnbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        grnbtn.setForeground(new java.awt.Color(255, 255, 255));
        grnbtn.setText("GRN");
        grnbtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/notepad.png"))); // NOI18N
        grnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grnbtnActionPerformed(evt);
            }
        });
        jPanel1.add(grnbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 223, 130, 39));

        vgrn.setBackground(new java.awt.Color(85, 160, 204));
        vgrn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        vgrn.setForeground(new java.awt.Color(255, 255, 255));
        vgrn.setText("All GRN");
        vgrn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/folder.png"))); // NOI18N
        vgrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vgrnActionPerformed(evt);
            }
        });
        jPanel1.add(vgrn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 273, 130, 39));

        vgrn1.setBackground(new java.awt.Color(85, 160, 204));
        vgrn1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        vgrn1.setForeground(new java.awt.Color(255, 255, 255));
        vgrn1.setText("Profit");
        vgrn1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pie-chart.png"))); // NOI18N
        vgrn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vgrn1ActionPerformed(evt);
            }
        });
        jPanel1.add(vgrn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 323, 130, 39));

        setting.setBackground(new java.awt.Color(85, 160, 204));
        setting.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        setting.setForeground(new java.awt.Color(255, 255, 255));
        setting.setText("Setting");
        setting.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shuffle.png"))); // NOI18N
        setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingActionPerformed(evt);
            }
        });
        jPanel1.add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 373, 130, 39));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 150, 680));

        center.setBackground(new java.awt.Color(255, 255, 255));
        center.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(center, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 1340, 670));

        jPanel3.setBackground(new java.awt.Color(107, 177, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        date.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jPanel3.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 120, 14));

        time.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jPanel3.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, 130, 14));

        signoutt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        signoutt.setText("Sign Out");
        signoutt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signoutt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signouttMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signouttMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signouttMouseExited(evt);
            }
        });
        jPanel3.add(signoutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, -1, -1));

        uname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        uname.setText("User Name :");
        jPanel3.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        utype.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        utype.setText("Admin");
        jPanel3.add(utype, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel2.setText("Date :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel3.setText("Time : ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("User :");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        sreq.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sreq.setText("Sign Up Request :0");
        sreq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sreq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sreqMouseClicked(evt);
            }
        });
        jPanel3.add(sreq, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        center.removeAll();
        this.setTitle("Add Item");
        GroupLayout layout = new javax.swing.GroupLayout(center);
        home.center.setLayout(layout);
        AddItem att = new AddItem();

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }//GEN-LAST:event_addActionPerformed

    private void vstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vstockActionPerformed
       center.removeAll();
       this.setTitle("View Stock");
        GroupLayout layout = new javax.swing.GroupLayout(center);
        home.center.setLayout(layout);
        ViewStock att = new ViewStock();

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }//GEN-LAST:event_vstockActionPerformed

    private void cinvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinvoiceActionPerformed
         center.removeAll();
         this.setTitle("Create Invoice");
        GroupLayout layout = new javax.swing.GroupLayout(center);
        home.center.setLayout(layout);
        CreateInvoice att = new CreateInvoice();

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }//GEN-LAST:event_cinvoiceActionPerformed

    private void vinvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vinvoiceActionPerformed
       center.removeAll();
         this.setTitle("View Invoice");
        GroupLayout layout = new javax.swing.GroupLayout(center);
        home.center.setLayout(layout);
        ViewInvoice att = new ViewInvoice();

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }//GEN-LAST:event_vinvoiceActionPerformed

    private void grnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grnbtnActionPerformed
       center.removeAll();
         this.setTitle("Good Received Note");
        GroupLayout layout = new javax.swing.GroupLayout(center);
        home.center.setLayout(layout);
        Grn att = new Grn();

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }//GEN-LAST:event_grnbtnActionPerformed

    private void vgrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vgrnActionPerformed
        center.removeAll();
         this.setTitle("View Good Resive Notes");
        GroupLayout layout = new javax.swing.GroupLayout(center);
        home.center.setLayout(layout);
        ViewGrn att = new ViewGrn();

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }//GEN-LAST:event_vgrnActionPerformed

    private void signouttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signouttMouseClicked
        Login lg=new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signouttMouseClicked

    private void signouttMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signouttMouseEntered
        signoutt.setText("<html><u>Sign Out</u></html>");
    }//GEN-LAST:event_signouttMouseEntered

    private void signouttMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signouttMouseExited
        signoutt.setText("Sign Out");
                                       
    }//GEN-LAST:event_signouttMouseExited

    private void sreqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sreqMouseClicked
          center.removeAll();
        this.setTitle("Sign Up Requests");
        GroupLayout layout = new javax.swing.GroupLayout(center);
        home.center.setLayout(layout);
        SignUpReq att = new SignUpReq();

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }//GEN-LAST:event_sreqMouseClicked

    private void settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingActionPerformed
        center.removeAll();
        this.setTitle("Change Password");
        GroupLayout layout = new javax.swing.GroupLayout(center);
        home.center.setLayout(layout);
        ChangeMyPassword att = new ChangeMyPassword();

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
    }//GEN-LAST:event_settingActionPerformed

    private void vgrn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vgrn1ActionPerformed
          center.removeAll();
        this.setTitle("Add Item");
        GroupLayout layout = new javax.swing.GroupLayout(center);
        home.center.setLayout(layout);
        profit att = new profit();

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

    }//GEN-LAST:event_vgrn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    public static javax.swing.JPanel center;
    private javax.swing.JButton cinvoice;
    public static javax.swing.JLabel date;
    private javax.swing.JButton grnbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton setting;
    private javax.swing.JLabel signoutt;
    private javax.swing.JLabel sreq;
    public static javax.swing.JLabel time;
    private javax.swing.JLabel uname;
    private javax.swing.JLabel utype;
    private javax.swing.JButton vgrn;
    private javax.swing.JButton vgrn1;
    private javax.swing.JButton vinvoice;
    private javax.swing.JButton vstock;
    // End of variables declaration//GEN-END:variables
}
