
import java.sql.ResultSet;
import java.text.SimpleDateFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author isuru
 */
public class profit extends javax.swing.JPanel {

    /**
     * Creates new form profit
     */
    public profit() {
        initComponents();
        try {
            String sql1="select sum(total) from tblinvoice";
            ResultSet rs1=db.dbConnection().executeQuery(sql1);
            if (rs1.next()) {                
                invo.setText("Rs "+rs1.getString(1));
            }
            
            String sql2="select sum(total) from tblgrn";
            ResultSet rs2=db.dbConnection().executeQuery(sql2);
             if (rs2.next()) {                
                grn.setText("Rs "+rs2.getString(1));
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        from = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        to = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        grn = new javax.swing.JLabel();
        invo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        from.setBackground(new java.awt.Color(255, 255, 255));
        from.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(from, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 30, 155, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("From");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 33, -1, -1));

        to.setBackground(new java.awt.Color(255, 255, 255));
        to.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 30, 155, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("To");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 33, -1, -1));

        grn.setBackground(new java.awt.Color(255, 255, 255));
        grn.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        grn.setForeground(new java.awt.Color(179, 57, 57));
        grn.setText("From");
        jPanel1.add(grn, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 150, 250, 100));

        invo.setBackground(new java.awt.Color(255, 255, 255));
        invo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        invo.setForeground(new java.awt.Color(33, 140, 116));
        invo.setText("From");
        jPanel1.add(invo, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 148, 240, 100));

        jButton1.setBackground(new java.awt.Color(52, 152, 219));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Filter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(179, 57, 57));
        jLabel3.setText("Expences");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(33, 140, 116));
        jLabel4.setText("Income");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {
            String a=new SimpleDateFormat("yyyy-MM-dd").format(from.getDate());
            String b=new SimpleDateFormat("yyyy-MM-dd").format(to.getDate());
            String sql1="select sum(total) from tblinvoice where date between '"+a+"' and '"+b+"'";
            ResultSet rs1=db.dbConnection().executeQuery(sql1);
            if (rs1.next()) {                
                invo.setText("Rs "+rs1.getString(1));
            }
            
            String sql2="select sum(total) from tblgrn where gdate between '"+a+"' and '"+b+"'";
            ResultSet rs2=db.dbConnection().executeQuery(sql2);
             if (rs2.next()) {                
                grn.setText("Rs "+rs2.getString(1));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser from;
    private javax.swing.JLabel grn;
    private javax.swing.JLabel invo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser to;
    // End of variables declaration//GEN-END:variables
}
