
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author isuru
 */
public class ViewGrn extends javax.swing.JPanel {

    /**
     * Creates new form ViewGrn
     */
    public ViewGrn() {
        initComponents();
        try {
            DefaultTableModel df=(DefaultTableModel) jTable1.getModel();
            String sql="select * from tblgrn";
            ResultSet rs=db.dbConnection().executeQuery(sql);
            while (rs.next()) {                
                 Vector v = new Vector();
                v.add(rs.getString("gid"));
                v.add(rs.getString("stotal"));
                v.add(rs.getString("discount"));
                v.add(rs.getString("total"));
                v.add(rs.getString("gdate"));
                v.add(rs.getString("gtime"));
                df.addRow(v);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        to = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        from = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Enter GRN Id");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 34, -1, -1));

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 31, 170, -1));

        jButton2.setBackground(new java.awt.Color(52, 152, 219));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Filter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, -1, -1));

        to.setBackground(new java.awt.Color(255, 255, 255));
        to.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 31, 161, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("From");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 34, -1, -1));

        from.setBackground(new java.awt.Color(255, 255, 255));
        from.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(from, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 31, 161, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("To");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 31, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "GRN Id", "Sub Total", "Discount", "Total", "Date", "Time"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 93, 888, 208));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Name", "Price", "Quentity", "Total price"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 319, 888, 185));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        try {
            DefaultTableModel df=(DefaultTableModel) jTable1.getModel();
            df.setRowCount(0);
            String sql="select * from tblgrn where gid like '%"+jTextField2.getText()+"%'";
            System.out.println(sql);
            ResultSet rs=db.dbConnection().executeQuery(sql);
            while (rs.next()) {                
                 Vector v = new Vector();
                v.add(rs.getString("gid"));
                v.add(rs.getString("stotal"));
                v.add(rs.getString("discount"));
                v.add(rs.getString("total"));
                v.add(rs.getString("gdate"));
                v.add(rs.getString("gtime"));
                df.addRow(v);
            }
            db.dbConnection().close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         
            int raw=jTable1.getSelectedRow();
             String clk=(jTable1.getModel().getValueAt(raw, 0).toString());
            //System.out.println(clk);
            try {
            DefaultTableModel df=(DefaultTableModel) jTable2.getModel();
            df.setRowCount(0);
            String sqltable="select * from grnitem inner join tblitem ON tblitem.id=grnitem.pid where grnitem.gid='"+clk+"'";
            ResultSet rs=db.dbConnection().executeQuery(sqltable);
            while(rs.next())
            {
                int q=Integer.parseInt(rs.getString("qty"));
                double p=Double.parseDouble(rs.getString("price"));
                
                Vector v = new Vector();
                v.add(rs.getString("pid"));
                v.add(rs.getString("name"));
                v.add(rs.getString("price"));
                v.add(rs.getString("qty"));
                v.add((q*p));
                
                df.addRow(v);
            }
        } catch (Exception e) {
                System.out.println(e);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
             DefaultTableModel df2=(DefaultTableModel) jTable2.getModel();
             df2.setRowCount(0);
            DefaultTableModel df=(DefaultTableModel) jTable1.getModel();
            df.setRowCount(0);
            String ap="";
            if(!jTextField2.getText().equals(""))
            {
              ap="gid like '%"+jTextField2.getText()+"%' and ";
            }
            String a=new SimpleDateFormat("yyyy-MM-dd").format(from.getDate());
            String b=new SimpleDateFormat("yyyy-MM-dd").format(to.getDate());
            String sql="select * from tblgrn where "+ap+" gdate between '"+a+"' and '"+b+"'";
            //System.out.println(sql);
            ResultSet rs=db.dbConnection().executeQuery(sql);
            while (rs.next()) {                
                 Vector v = new Vector();
                v.add(rs.getString("gid"));
                v.add(rs.getString("stotal"));
                v.add(rs.getString("discount"));
                v.add(rs.getString("total"));
                v.add(rs.getString("gdate"));
                v.add(rs.getString("gtime"));
                df.addRow(v);
            }
            db.dbConnection().close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser from;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private com.toedter.calendar.JDateChooser to;
    // End of variables declaration//GEN-END:variables
}
